-- Populate tblStore
BEGIN TRAN populateStore
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('Costco', '8629 120th Ave NE', 'Kirkland', 'Washington WA', 98033, 150000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('Costco', '4401 4th Ave S', 'Seattle', 'Washington WA', 98134, 142000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('QFC', '2746 45th St NE', 'Seattle', 'Washington WA', 98105, 45000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('QFC', '1801 45th St N', 'Seattle', 'Washington WA', 98103, 57000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('Trader Joe''s', '4555 Roosevelt Way NE', 'Seattle', 'Washington WA', 98105, 20000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('Trader Joe''s', '1916 Queen Anne Ave N', 'Seattle', 'Washington WA', 98109, 18500)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('H Mart', '4216 University Way NE', 'Seattle', 'Washington WA', 98105, 200)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('H Mart', '100 108th Ave NE', 'Bellevue', 'Washington WA', 98004, 34000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('99 Ranch Market', '22511 Hwy 99', 'Edmonds', 'Washington WA', 98026, 12000)
    INSERT INTO tblStore(StoreName, StoreAddress, StoreCity, StoreState, StoreZipcode, StoreSize)
    VALUES ('99 Ranch Market', '18230 E Valley Hwy', 'Kent', 'Washington WA', 98032, 10500)
COMMIT TRAN populateStore