
USE INFO330_PROJ_A13
BEGIN TRAN populateBrand
insert into tblBrand (BrandName, CompanyID) values ('Raisin - Golden', 28);
insert into tblBrand (BrandName, CompanyID) values ('Pastry - Lemon Danish - Mini', 65);
insert into tblBrand (BrandName, CompanyID) values ('Nantucket - Orange Mango Cktl', 73);
insert into tblBrand (BrandName, CompanyID) values ('Fennel - Seeds', 2);
insert into tblBrand (BrandName, CompanyID) values ('Flour - So Mix Cake White', 92);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Chateau Aqueria Tavel', 95);
insert into tblBrand (BrandName, CompanyID) values ('Cocoa Butter', 4);
insert into tblBrand (BrandName, CompanyID) values ('Catfish - Fillets', 21);
insert into tblBrand (BrandName, CompanyID) values ('Bay Leaf Fresh', 97);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Clamato, 341 Ml', 56);
insert into tblBrand (BrandName, CompanyID) values ('Brandy Apricot', 74);
insert into tblBrand (BrandName, CompanyID) values ('Carrots - Mini Red Organic', 81);
insert into tblBrand (BrandName, CompanyID) values ('Pate - Liver', 16);
insert into tblBrand (BrandName, CompanyID) values ('Steampan - Half Size Shallow', 33);
insert into tblBrand (BrandName, CompanyID) values ('Pastry - Baked Scones - Mini', 93);
insert into tblBrand (BrandName, CompanyID) values ('Cotton Wet Mop 16 Oz', 65);
insert into tblBrand (BrandName, CompanyID) values ('Energy Drink', 54);
insert into tblBrand (BrandName, CompanyID) values ('Plums - Red', 37);
insert into tblBrand (BrandName, CompanyID) values ('Onions - Red Pearl', 73);
insert into tblBrand (BrandName, CompanyID) values ('Radish', 96);
insert into tblBrand (BrandName, CompanyID) values ('Vinegar - Balsamic, White', 85);
insert into tblBrand (BrandName, CompanyID) values ('Grand Marnier', 10);
insert into tblBrand (BrandName, CompanyID) values ('Miso - Soy Bean Paste', 19);
insert into tblBrand (BrandName, CompanyID) values ('Lighter - Bbq', 55);
insert into tblBrand (BrandName, CompanyID) values ('Vaccum Bag 10x13', 97);
insert into tblBrand (BrandName, CompanyID) values ('Tomatoes - Heirloom', 22);
insert into tblBrand (BrandName, CompanyID) values ('Cornish Hen', 43);
insert into tblBrand (BrandName, CompanyID) values ('Potatoes - Pei 10 Oz', 78);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Chablis J Moreau Et Fils', 21);
insert into tblBrand (BrandName, CompanyID) values ('Bread Base - Goodhearth', 11);
insert into tblBrand (BrandName, CompanyID) values ('Asparagus - Green, Fresh', 2);
insert into tblBrand (BrandName, CompanyID) values ('Chilli Paste, Sambal Oelek', 64);
insert into tblBrand (BrandName, CompanyID) values ('Milk - Buttermilk', 40);
insert into tblBrand (BrandName, CompanyID) values ('Sausage - Blood Pudding', 58);
insert into tblBrand (BrandName, CompanyID) values ('Snapple - Mango Maddness', 90);
insert into tblBrand (BrandName, CompanyID) values ('Brownies - Two Bite, Chocolate', 94);
insert into tblBrand (BrandName, CompanyID) values ('Herb Du Provence - Primerba', 83);
insert into tblBrand (BrandName, CompanyID) values ('Carbonated Water - Peach', 4);
insert into tblBrand (BrandName, CompanyID) values ('Split Peas - Green, Dry', 28);
insert into tblBrand (BrandName, CompanyID) values ('Sparkling Wine - Rose, Freixenet', 62);
insert into tblBrand (BrandName, CompanyID) values ('Sproutsmustard Cress', 53);
insert into tblBrand (BrandName, CompanyID) values ('Papayas', 40);
insert into tblBrand (BrandName, CompanyID) values ('Cloves - Whole', 39);
insert into tblBrand (BrandName, CompanyID) values ('Smoked Paprika', 68);
insert into tblBrand (BrandName, CompanyID) values ('Bread Fig And Almond', 2);
insert into tblBrand (BrandName, CompanyID) values ('Flour - Rye', 88);
insert into tblBrand (BrandName, CompanyID) values ('Chicken - Bones', 58);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Mozzarella', 48);
insert into tblBrand (BrandName, CompanyID) values ('Grapes - Black', 36);
insert into tblBrand (BrandName, CompanyID) values ('Tomatoes - Heirloom', 19);
insert into tblBrand (BrandName, CompanyID) values ('Lamb - Leg, Bone In', 78);
insert into tblBrand (BrandName, CompanyID) values ('Oil - Truffle, White', 99);
insert into tblBrand (BrandName, CompanyID) values ('Sour Cream', 3);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Savigny - Les - Beaune', 25);
insert into tblBrand (BrandName, CompanyID) values ('Sansho Powder', 84);
insert into tblBrand (BrandName, CompanyID) values ('Rosemary - Primerba, Paste', 47);
insert into tblBrand (BrandName, CompanyID) values ('Toamtoes 6x7 Select', 18);
insert into tblBrand (BrandName, CompanyID) values ('Broom - Corn', 83);
insert into tblBrand (BrandName, CompanyID) values ('Ice Cream Bar - Oreo Cone', 81);
insert into tblBrand (BrandName, CompanyID) values ('Oil - Food, Lacquer Spray', 51);
insert into tblBrand (BrandName, CompanyID) values ('Potatoes - Mini Red', 77);
insert into tblBrand (BrandName, CompanyID) values ('Pesto - Primerba, Paste', 85);
insert into tblBrand (BrandName, CompanyID) values ('Corn - Mini', 52);
insert into tblBrand (BrandName, CompanyID) values ('Pasta - Elbows, Macaroni, Dry', 12);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Chateau Aqueria Tavel', 95);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Multigrain Oval', 79);
insert into tblBrand (BrandName, CompanyID) values ('Syrup - Monin - Passion Fruit', 70);
insert into tblBrand (BrandName, CompanyID) values ('Vodka - Moskovskaya', 37);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Niagara Peninsula Vqa', 34);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - Baby, Warm Water', 89);
insert into tblBrand (BrandName, CompanyID) values ('Doilies - 8, Paper', 39);
insert into tblBrand (BrandName, CompanyID) values ('Buttons', 5);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Prosecco Valdobienne', 6);
insert into tblBrand (BrandName, CompanyID) values ('Canadian Emmenthal', 65);
insert into tblBrand (BrandName, CompanyID) values ('Cookie Dough - Chunky', 2);
insert into tblBrand (BrandName, CompanyID) values ('Nut - Pine Nuts, Whole', 96);
insert into tblBrand (BrandName, CompanyID) values ('Soup - Campbells, Beef Barley', 54);
insert into tblBrand (BrandName, CompanyID) values ('Butter - Salted, Micro', 64);
insert into tblBrand (BrandName, CompanyID) values ('Butter Ripple - Phillips', 11);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - 16/20, Peeled Deviened', 38);
insert into tblBrand (BrandName, CompanyID) values ('Brownies - Two Bite, Chocolate', 40);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Orange, 341 Ml', 57);
insert into tblBrand (BrandName, CompanyID) values ('Ham - Virginia', 19);
insert into tblBrand (BrandName, CompanyID) values ('Monkfish - Fresh', 88);
insert into tblBrand (BrandName, CompanyID) values ('Flour Pastry Super Fine', 15);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Hardys Bankside Shiraz', 69);
insert into tblBrand (BrandName, CompanyID) values ('Veal - Shank, Pieces', 21);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Magnotta - Bel Paese White', 23);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Red, Cabernet Sauvignon', 84);
insert into tblBrand (BrandName, CompanyID) values ('Longos - Greek Salad', 15);
insert into tblBrand (BrandName, CompanyID) values ('Jolt Cola', 70);
insert into tblBrand (BrandName, CompanyID) values ('Beans - Long, Chinese', 63);
insert into tblBrand (BrandName, CompanyID) values ('Apron', 3);
insert into tblBrand (BrandName, CompanyID) values ('Asparagus - Frozen', 89);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Dubouef Macon - Villages', 50);
insert into tblBrand (BrandName, CompanyID) values ('Flavouring - Raspberry', 31);
insert into tblBrand (BrandName, CompanyID) values ('Longos - Assorted Sandwich', 67);
insert into tblBrand (BrandName, CompanyID) values ('Praline Paste', 36);
insert into tblBrand (BrandName, CompanyID) values ('Tart Shells - Savory, 4', 56);
insert into tblBrand (BrandName, CompanyID) values ('Muffin Puck Ww Carrot', 80);
COMMIT TRAN populateBrand

insert into tblBrand (BrandName, CompanyID) values ('Squid - U - 10 Thailand', 26);
insert into tblBrand (BrandName, CompanyID) values ('Turkey - Breast, Boneless Sk On', 32);
insert into tblBrand (BrandName, CompanyID) values ('Flour - Whole Wheat', 67);
insert into tblBrand (BrandName, CompanyID) values ('Glycerine', 16);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Kidney', 60);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Roll, Italian', 41);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Olive', 28);
insert into tblBrand (BrandName, CompanyID) values ('Tea - Grapefruit Green Tea', 69);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Gouda Smoked', 85);
insert into tblBrand (BrandName, CompanyID) values ('Octopus', 12);
insert into tblBrand (BrandName, CompanyID) values ('Fish - Bones', 66);
insert into tblBrand (BrandName, CompanyID) values ('Vinegar - Raspberry', 84);
insert into tblBrand (BrandName, CompanyID) values ('Chervil - Fresh', 30);
insert into tblBrand (BrandName, CompanyID) values ('Puree - Guava', 100);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Jackson Triggs Okonagan', 33);
insert into tblBrand (BrandName, CompanyID) values ('Beer - Alexander Kieths, Pale Ale', 44);
insert into tblBrand (BrandName, CompanyID) values ('Basil - Thai', 84);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Lime', 78);
insert into tblBrand (BrandName, CompanyID) values ('Cake - Lemon Chiffon', 15);
insert into tblBrand (BrandName, CompanyID) values ('Red Snapper - Fresh, Whole', 72);
insert into tblBrand (BrandName, CompanyID) values ('Rappini - Andy Boy', 51);
insert into tblBrand (BrandName, CompanyID) values ('Crab - Blue, Frozen', 65);
insert into tblBrand (BrandName, CompanyID) values ('Piping Jelly - All Colours', 36);
insert into tblBrand (BrandName, CompanyID) values ('Quail - Jumbo', 9);
insert into tblBrand (BrandName, CompanyID) values ('Beef Striploin Aaa', 29);
insert into tblBrand (BrandName, CompanyID) values ('Wiberg Cure', 93);
insert into tblBrand (BrandName, CompanyID) values ('Evaporated Milk - Skim', 17);
insert into tblBrand (BrandName, CompanyID) values ('V8 Splash Strawberry Banana', 81);
insert into tblBrand (BrandName, CompanyID) values ('Miso Paste White', 59);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - Black Tiger 26/30', 14);
insert into tblBrand (BrandName, CompanyID) values ('Jam - Marmalade, Orange', 92);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Red, Gallo, Merlot', 25);
insert into tblBrand (BrandName, CompanyID) values ('Sauce - Demi Glace', 7);
insert into tblBrand (BrandName, CompanyID) values ('Chicken - White Meat, No Tender', 53);
insert into tblBrand (BrandName, CompanyID) values ('Veal - Inside Round / Top, Lean', 13);
insert into tblBrand (BrandName, CompanyID) values ('Rye Special Old', 62);
insert into tblBrand (BrandName, CompanyID) values ('Salmon - Canned', 57);
insert into tblBrand (BrandName, CompanyID) values ('Bread Base - Goodhearth', 43);

insert into tblBrand (BrandName, CompanyID) values ('Creme De Menthe Green', 29);
insert into tblBrand (BrandName, CompanyID) values ('Alize Sunset', 40);
insert into tblBrand (BrandName, CompanyID) values ('Muffin - Zero Transfat', 92);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Ruffino Chianti', 98);
insert into tblBrand (BrandName, CompanyID) values ('Pineapple - Golden', 13);
insert into tblBrand (BrandName, CompanyID) values ('Sauce - Ranch Dressing', 57);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Bourgogne 2002, La', 33);
insert into tblBrand (BrandName, CompanyID) values ('Lettuce Romaine Chopped', 79);
insert into tblBrand (BrandName, CompanyID) values ('Sachet', 52);
insert into tblBrand (BrandName, CompanyID) values ('Jello - Assorted', 35);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Loin, Center Cut', 59);
insert into tblBrand (BrandName, CompanyID) values ('Soup Campbells Turkey Veg.', 77);
insert into tblBrand (BrandName, CompanyID) values ('Muffins - Assorted', 27);
insert into tblBrand (BrandName, CompanyID) values ('Table Cloth 62x120 Colour', 33);
insert into tblBrand (BrandName, CompanyID) values ('Lettuce - Lambs Mash', 28);
insert into tblBrand (BrandName, CompanyID) values ('Shark - Loin', 7);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Tenderloin, Frozen', 41);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Brie, Cups 125g', 84);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Ciabatta Buns', 79);
insert into tblBrand (BrandName, CompanyID) values ('Ranchero - Primerba, Paste', 67);
insert into tblBrand (BrandName, CompanyID) values ('Lotus Rootlets - Canned', 90);
insert into tblBrand (BrandName, CompanyID) values ('Smirnoff Green Apple Twist', 44);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Cranberry 284ml', 93);
insert into tblBrand (BrandName, CompanyID) values ('Tofu - Soft', 99);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Smoked Back Bacon', 8);
insert into tblBrand (BrandName, CompanyID) values ('Sausage - Andouille', 39);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Apple Cider', 18);
insert into tblBrand (BrandName, CompanyID) values ('Tray - Foam, Square 4 - S', 40);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Tomato, 10 Oz', 75);
insert into tblBrand (BrandName, CompanyID) values ('Carrots - Mini Red Organic', 58);
insert into tblBrand (BrandName, CompanyID) values ('Chef Hat 20cm', 59);
insert into tblBrand (BrandName, CompanyID) values ('Appetizer - Mini Egg Roll, Shrimp', 12);
insert into tblBrand (BrandName, CompanyID) values ('Rice - Sushi', 72);
insert into tblBrand (BrandName, CompanyID) values ('Rappini - Andy Boy', 28);
insert into tblBrand (BrandName, CompanyID) values ('Basil - Dry, Rubbed', 67);
insert into tblBrand (BrandName, CompanyID) values ('Potatoes - Mini Red', 80);
insert into tblBrand (BrandName, CompanyID) values ('Long Island Ice Tea', 30);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Bistro Sour', 49);

insert into tblBrand (BrandName, CompanyID) values ('Beer - Sleemans Honey Brown', 36);
insert into tblBrand (BrandName, CompanyID) values ('Soup Campbells Split Pea And Ham', 89);
insert into tblBrand (BrandName, CompanyID) values ('Tamarind Paste', 74);
insert into tblBrand (BrandName, CompanyID) values ('Muffin Mix - Blueberry', 5);
insert into tblBrand (BrandName, CompanyID) values ('Tomato - Plum With Basil', 43);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Montery Jack', 14);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - 31/40', 54);
insert into tblBrand (BrandName, CompanyID) values ('Crab - Meat Combo', 26);
insert into tblBrand (BrandName, CompanyID) values ('Sprouts - Onion', 5);
insert into tblBrand (BrandName, CompanyID) values ('Noodles - Steamed Chow Mein', 5);
insert into tblBrand (BrandName, CompanyID) values ('Bar Mix - Lemon', 86);
insert into tblBrand (BrandName, CompanyID) values ('Cookies - Amaretto', 16);
insert into tblBrand (BrandName, CompanyID) values ('Beans - Green', 16);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Pita', 94);
insert into tblBrand (BrandName, CompanyID) values ('Scallops 60/80 Iqf', 26);
insert into tblBrand (BrandName, CompanyID) values ('Veal - Inside', 93);
insert into tblBrand (BrandName, CompanyID) values ('Wine - White, Ej', 33);
insert into tblBrand (BrandName, CompanyID) values ('Oil - Macadamia', 95);
insert into tblBrand (BrandName, CompanyID) values ('Lid - Translucent, 3.5 And 6 Oz', 18);
insert into tblBrand (BrandName, CompanyID) values ('Onions - Cooking', 38);
insert into tblBrand (BrandName, CompanyID) values ('Veal - Inside', 97);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Crusty Italian Poly', 52);
insert into tblBrand (BrandName, CompanyID) values ('Beef Tenderloin Aaa', 28);
insert into tblBrand (BrandName, CompanyID) values ('Oven Mitts 17 Inch', 81);
insert into tblBrand (BrandName, CompanyID) values ('Beans - Turtle, Black, Dry', 15);
insert into tblBrand (BrandName, CompanyID) values ('Browning Caramel Glace', 37);
insert into tblBrand (BrandName, CompanyID) values ('Onions - Spanish', 88);
insert into tblBrand (BrandName, CompanyID) values ('Coffee - Beans, Whole', 13);
insert into tblBrand (BrandName, CompanyID) values ('Onions - White', 6);
insert into tblBrand (BrandName, CompanyID) values ('Eggplant - Baby', 7);
insert into tblBrand (BrandName, CompanyID) values ('Oranges', 66);
insert into tblBrand (BrandName, CompanyID) values ('Champagne - Brights, Dry', 93);
insert into tblBrand (BrandName, CompanyID) values ('Stainless Steel Cleaner Vision', 100);
insert into tblBrand (BrandName, CompanyID) values ('Tart - Butter Plain Squares', 82);
insert into tblBrand (BrandName, CompanyID) values ('Wine - White, Riesling, Semi - Dry', 85);
insert into tblBrand (BrandName, CompanyID) values ('Rosemary - Primerba, Paste', 42);
insert into tblBrand (BrandName, CompanyID) values ('Split Peas - Green, Dry', 14);


insert into tblBrand (BrandName, CompanyID) values ('Nantucket - Pomegranate Pear', 33);
insert into tblBrand (BrandName, CompanyID) values ('Carbonated Water - Blackcherry', 39);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Bakers Cream Cheese', 33);
insert into tblBrand (BrandName, CompanyID) values ('Onion - Dried', 18);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Wine', 50);
insert into tblBrand (BrandName, CompanyID) values ('Fish - Halibut, Cold Smoked', 18);
insert into tblBrand (BrandName, CompanyID) values ('Beans - Kidney, Canned', 24);
insert into tblBrand (BrandName, CompanyID) values ('Club Soda - Schweppes, 355 Ml', 6);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Apple, 341 Ml', 48);
insert into tblBrand (BrandName, CompanyID) values ('Versatainer Nc - 8288', 42);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Provolone', 29);
insert into tblBrand (BrandName, CompanyID) values ('Ice Cream - Chocolate', 14);
insert into tblBrand (BrandName, CompanyID) values ('Dc - Frozen Momji', 34);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - Black Tiger 13/15', 44);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Back, Long Cut, Boneless', 21);
insert into tblBrand (BrandName, CompanyID) values ('Carroway Seed', 33);
insert into tblBrand (BrandName, CompanyID) values ('Container Clear 8 Oz', 15);
insert into tblBrand (BrandName, CompanyID) values ('Fireball Whisky', 19);
insert into tblBrand (BrandName, CompanyID) values ('Aspic - Clear', 44);
insert into tblBrand (BrandName, CompanyID) values ('Chinese Foods - Plain Fried Rice', 20);
insert into tblBrand (BrandName, CompanyID) values ('Sauce - Hollandaise', 36);
insert into tblBrand (BrandName, CompanyID) values ('Flounder - Fresh', 2);
insert into tblBrand (BrandName, CompanyID) values ('Onions - Red', 43);
insert into tblBrand (BrandName, CompanyID) values ('Honey - Comb', 19);
insert into tblBrand (BrandName, CompanyID) values ('Wine - White, Riesling, Semi - Dry', 24);
insert into tblBrand (BrandName, CompanyID) values ('Gooseberry', 11);
insert into tblBrand (BrandName, CompanyID) values ('Lime Cordial - Roses', 17);
insert into tblBrand (BrandName, CompanyID) values ('Beer - Rickards Red', 1);
insert into tblBrand (BrandName, CompanyID) values ('Macaroons - Two Bite Choc', 7);
insert into tblBrand (BrandName, CompanyID) values ('Foil Wrap', 32);
insert into tblBrand (BrandName, CompanyID) values ('Trout Rainbow Whole', 37);
insert into tblBrand (BrandName, CompanyID) values ('Syrup - Pancake', 16);
insert into tblBrand (BrandName, CompanyID) values ('Gatorade - Xfactor Berry', 1);
insert into tblBrand (BrandName, CompanyID) values ('Kale - Red', 3);
insert into tblBrand (BrandName, CompanyID) values ('Madeira', 39);
insert into tblBrand (BrandName, CompanyID) values ('Chilli Paste, Ginger Garlic', 3);


insert into tblBrand (BrandName, CompanyID) values ('Lidsoupcont Rp12dn', 1);
insert into tblBrand (BrandName, CompanyID) values ('Lotus Rootlets - Canned', 1);
insert into tblBrand (BrandName, CompanyID) values ('Sugar - Brown, Individual', 1);
insert into tblBrand (BrandName, CompanyID) values ('Sugar - Brown, Individual', 1);
insert into tblBrand (BrandName, CompanyID) values ('Chicken Breast Wing On', 1);
insert into tblBrand (BrandName, CompanyID) values ('Sugar - Palm', 1);
insert into tblBrand (BrandName, CompanyID) values ('Rice - Aborio', 1);
insert into tblBrand (BrandName, CompanyID) values ('Salmon - Atlantic, Skin On', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Gouda Smoked', 1);
insert into tblBrand (BrandName, CompanyID) values ('The Pop Shoppe - Cream Soda', 1);
insert into tblBrand (BrandName, CompanyID) values ('Mayonnaise - Individual Pkg', 1);
insert into tblBrand (BrandName, CompanyID) values ('Bacon Strip Precooked', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Goat', 1);
insert into tblBrand (BrandName, CompanyID) values ('Veal - Heart', 1);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Shoulder', 1);
insert into tblBrand (BrandName, CompanyID) values ('Tomatoes - Heirloom', 1);
insert into tblBrand (BrandName, CompanyID) values ('Pork - Backfat', 1);
insert into tblBrand (BrandName, CompanyID) values ('Nut - Peanut, Roasted', 1);
insert into tblBrand (BrandName, CompanyID) values ('Bar Special K', 1);
insert into tblBrand (BrandName, CompanyID) values ('Fennel - Seeds', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Brie Roitelet', 1);
insert into tblBrand (BrandName, CompanyID) values ('Tart Shells - Savory, 2', 1);
insert into tblBrand (BrandName, CompanyID) values ('Calypso - Black Cherry Lemonade', 1);
insert into tblBrand (BrandName, CompanyID) values ('Turkey Tenderloin Frozen', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cleaner - Lime Away', 1);
insert into tblBrand (BrandName, CompanyID) values ('Peas - Frozen', 1);
insert into tblBrand (BrandName, CompanyID) values ('Container - Hngd Cll Blk 7x7x3', 1);
insert into tblBrand (BrandName, CompanyID) values ('Danishes - Mini Cheese', 1);
insert into tblBrand (BrandName, CompanyID) values ('Vegetable - Base', 1);
insert into tblBrand (BrandName, CompanyID) values ('Radish', 1);
insert into tblBrand (BrandName, CompanyID) values ('Syrup - Chocolate', 1);
insert into tblBrand (BrandName, CompanyID) values ('Oil - Margarine', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cloves - Ground', 1);
insert into tblBrand (BrandName, CompanyID) values ('Pur Source', 1);
insert into tblBrand (BrandName, CompanyID) values ('Dates', 1);
insert into tblBrand (BrandName, CompanyID) values ('Remy Red', 1);