
USE INFO330_PROJ_A13

insert into tblBrand (BrandName, CompanyID) values ('Caduet', 66);
insert into tblBrand (BrandName, CompanyID) values ('LBEL', 97);
insert into tblBrand (BrandName, CompanyID) values ('Loxapine', 42);
insert into tblBrand (BrandName, CompanyID) values ('Gabapentin', 23);
insert into tblBrand (BrandName, CompanyID) values ('Viscum 1', 69);
insert into tblBrand (BrandName, CompanyID) values ('Anu-Med', 9);
insert into tblBrand (BrandName, CompanyID) values ('Non-Aspirin', 49);
insert into tblBrand (BrandName, CompanyID) values ('EQUALINE', 76);
insert into tblBrand (BrandName, CompanyID) values ('Mirtazapine', 17);
insert into tblBrand (BrandName, CompanyID) values ('CALCAREA FLUORICA', 90);
insert into tblBrand (BrandName, CompanyID) values ('NEW DOCTOR AG PLUS', 49);
insert into tblBrand (BrandName, CompanyID) values ('Chrysolith 6', 43);
insert into tblBrand (BrandName, CompanyID) values ('Stool Softener', 88);
insert into tblBrand (BrandName, CompanyID) values ('Ranitidine', 9);
insert into tblBrand (BrandName, CompanyID) values ('Zafirlukast', 16);
insert into tblBrand (BrandName, CompanyID) values ('Geodon', 23);
insert into tblBrand (BrandName, CompanyID) values ('Carbon Dioxide', 67);
insert into tblBrand (BrandName, CompanyID) values ('Demser', 65);
insert into tblBrand (BrandName, CompanyID) values ('Galantamine', 97);
insert into tblBrand (BrandName, CompanyID) values ('Oxygen', 100);
insert into tblBrand (BrandName, CompanyID) values ('Armour Thyroid', 86);
insert into tblBrand (BrandName, CompanyID) values ('Glipizide', 3);
insert into tblBrand (BrandName, CompanyID) values ('NECON 1/35', 54);
insert into tblBrand (BrandName, CompanyID) values ('Analgesic', 86);
insert into tblBrand (BrandName, CompanyID) values ('Pleo Muc', 25);
insert into tblBrand (BrandName, CompanyID) values ('Dextrose', 20);
insert into tblBrand (BrandName, CompanyID) values ('Echinacea e rad. 50', 57);
insert into tblBrand (BrandName, CompanyID) values ('Zolpidem Tartrate', 89);
insert into tblBrand (BrandName, CompanyID) values ('Carisoprodol', 1);
insert into tblBrand (BrandName, CompanyID) values ('Spironolactone', 58);
insert into tblBrand (BrandName, CompanyID) values ('STAVUDINE', 10);
insert into tblBrand (BrandName, CompanyID) values ('Rough Marsh Elder', 41);
insert into tblBrand (BrandName, CompanyID) values ('Oxazepam', 15);


insert into tblBrand (BrandName, CompanyID) values ('Mizani Scalp Care Antidandruff', 1);
insert into tblBrand (BrandName, CompanyID) values ('Sun-Kissed Lip Balm', 1);
insert into tblBrand (BrandName, CompanyID) values ('SKIN PROTECTANT', 1);
insert into tblBrand (BrandName, CompanyID) values ('CLE DE PEAU BEAUTE SILKY FOUNDATION I', 1);
insert into tblBrand (BrandName, CompanyID) values ('Selenium', 1);
insert into tblBrand (BrandName, CompanyID) values ('Mirtazapine', 1);
insert into tblBrand (BrandName, CompanyID) values ('Hydrocodone Bitartrate and Acetaminophen', 1);
insert into tblBrand (BrandName, CompanyID) values ('Azulfidine', 1);
insert into tblBrand (BrandName, CompanyID) values ('Dolce and Gabbana The Foundation Perfect Matte', 1);
insert into tblBrand (BrandName, CompanyID) values ('Hydrocodone Bitartrate and Ibuprofen', 1);
insert into tblBrand (BrandName, CompanyID) values ('Burn Jel Plus', 1);
insert into tblBrand (BrandName, CompanyID) values ('nicotine', 1);
insert into tblBrand (BrandName, CompanyID) values ('Egg White', 1);
insert into tblBrand (BrandName, CompanyID) values ('Tobramycin and Dexamethasone', 1);
insert into tblBrand (BrandName, CompanyID) values ('Motion sickness', 1);
insert into tblBrand (BrandName, CompanyID) values ('Restless Leg', 1);
insert into tblBrand (BrandName, CompanyID) values ('Colds Yellow Mucous', 1);
insert into tblBrand (BrandName, CompanyID) values ('Vanilla Cream Antibacterial Hand Wash', 1);
insert into tblBrand (BrandName, CompanyID) values ('SPORANOX', 1);
insert into tblBrand (BrandName, CompanyID) values ('SENSAI FLUID FINISH LASTING VELVET FV204.5', 1);
insert into tblBrand (BrandName, CompanyID) values ('up and up ibuprofen', 1);
insert into tblBrand (BrandName, CompanyID) values ('Dr. Numb', 1);
insert into tblBrand (BrandName, CompanyID) values ('Alba Botanica UN-petroleum Cherry SPF18 Lip Balm', 1);
insert into tblBrand (BrandName, CompanyID) values ('Backache Relief', 1);
insert into tblBrand (BrandName, CompanyID) values ('Diphenhydramine Hydrochloride', 1);
insert into tblBrand (BrandName, CompanyID) values ('Body Wash', 1);
insert into tblBrand (BrandName, CompanyID) values ('Clorazepate Dipotassium', 1);
insert into tblBrand (BrandName, CompanyID) values ('RE-PB HYOS ELIXIR', 1);
insert into tblBrand (BrandName, CompanyID) values ('Kmart Corporation', 1);
insert into tblBrand (BrandName, CompanyID) values ('Okyong pack', 1);
insert into tblBrand (BrandName, CompanyID) values ('Donepezil Hydrochloride', 1);
insert into tblBrand (BrandName, CompanyID) values ('Sulindac', 1);
insert into tblBrand (BrandName, CompanyID) values ('Sun Shades Lip Balm', 1);
insert into tblBrand (BrandName, CompanyID) values ('Amiodarone Hydrochloride', 1);
insert into tblBrand (BrandName, CompanyID) values ('Warfarin Sodium', 1);
insert into tblBrand (BrandName, CompanyID) values ('Dog Hair', 1);

insert into tblBrand (BrandName, CompanyID) values ('Estradiol', 86);
insert into tblBrand (BrandName, CompanyID) values ('Topcare Childrens Pain Relief', 44);
insert into tblBrand (BrandName, CompanyID) values ('Quetiapine fumarate', 57);
insert into tblBrand (BrandName, CompanyID) values ('Ondansetron Hydrochloride and Dextrose', 40);
insert into tblBrand (BrandName, CompanyID) values ('Up and Up Cold Flu Relief Day Night', 93);
insert into tblBrand (BrandName, CompanyID) values ('Morphine Sulfate', 32);
insert into tblBrand (BrandName, CompanyID) values ('ORRIS ROOT', 94);
insert into tblBrand (BrandName, CompanyID) values ('HEB', 42);
insert into tblBrand (BrandName, CompanyID) values ('Pantoprazole Sodium', 44);
insert into tblBrand (BrandName, CompanyID) values ('Docusate Sodium Stool Softener', 43);
insert into tblBrand (BrandName, CompanyID) values ('Levetiracetam', 101);
insert into tblBrand (BrandName, CompanyID) values ('Neutrogena MoistureShine SPF20', 24);
insert into tblBrand (BrandName, CompanyID) values ('PARAID One Step Wart Remover Strips', 63);
insert into tblBrand (BrandName, CompanyID) values ('CLOSE UP', 90);
insert into tblBrand (BrandName, CompanyID) values ('Levothyroxine Sodium', 53);
insert into tblBrand (BrandName, CompanyID) values ('Glimepiride', 7);
insert into tblBrand (BrandName, CompanyID) values ('Good Mood Enhancer', 12);
insert into tblBrand (BrandName, CompanyID) values ('Minipress', 85);
insert into tblBrand (BrandName, CompanyID) values ('Carvedilol', 20);
insert into tblBrand (BrandName, CompanyID) values ('AHC Vital C Complex Mask', 12);
insert into tblBrand (BrandName, CompanyID) values ('Isoniazid', 66);
insert into tblBrand (BrandName, CompanyID) values ('SODIUM SULFACETAMIDE AND SULFUR', 77);
insert into tblBrand (BrandName, CompanyID) values ('OXYGEN', 44);
insert into tblBrand (BrandName, CompanyID) values ('Maxiphen', 4);
insert into tblBrand (BrandName, CompanyID) values ('Smart Sense Hemorrhoidal', 5);
insert into tblBrand (BrandName, CompanyID) values ('ShopRite Sleep Aid', 87);
insert into tblBrand (BrandName, CompanyID) values ('Amlodipine Besylate', 67);
insert into tblBrand (BrandName, CompanyID) values ('piperacillin and tazobactam', 55);
insert into tblBrand (BrandName, CompanyID) values ('Medrox', 29);
insert into tblBrand (BrandName, CompanyID) values ('Quetiapine fumarate', 19);
insert into tblBrand (BrandName, CompanyID) values ('Donepezil Hydrochloride', 20);
insert into tblBrand (BrandName, CompanyID) values ('Nite Time Day Time', 9);

insert into tblBrand (BrandName, CompanyID) values ('OxyContin', 1);
insert into tblBrand (BrandName, CompanyID) values ('Amlodipine Besylate', 1);
insert into tblBrand (BrandName, CompanyID) values ('Zemplar', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cyclobenzaprine Hydrochloride', 1);
insert into tblBrand (BrandName, CompanyID) values ('Doxorubicin Hydrochloride', 1);
insert into tblBrand (BrandName, CompanyID) values ('Pravastatin Sodium', 1);
insert into tblBrand (BrandName, CompanyID) values ('TOPIRAMATE', 1);
insert into tblBrand (BrandName, CompanyID) values ('Enviro', 1);
insert into tblBrand (BrandName, CompanyID) values ('Morning Sickness', 1);
insert into tblBrand (BrandName, CompanyID) values ('TOPCARE', 1);
insert into tblBrand (BrandName, CompanyID) values ('FENTANYL TRANSDERMAL SYSTEM', 1);
insert into tblBrand (BrandName, CompanyID) values ('Colgate Optic White Sparkling Mint', 1);
insert into tblBrand (BrandName, CompanyID) values ('Childrens Loratadine', 1);
insert into tblBrand (BrandName, CompanyID) values ('Cough Complex', 1);
insert into tblBrand (BrandName, CompanyID) values ('Banana Boat Kids Protect and Play SPF 85', 1);
insert into tblBrand (BrandName, CompanyID) values ('Uroxatral', 1);
insert into tblBrand (BrandName, CompanyID) values ('Diazepam', 1);
insert into tblBrand (BrandName, CompanyID) values ('Acetaminophen Rapid Release', 1);
insert into tblBrand (BrandName, CompanyID) values ('AMERGE', 1);
insert into tblBrand (BrandName, CompanyID) values ('Levothyroxine Sodium', 1);
insert into tblBrand (BrandName, CompanyID) values ('PVP Prep', 1);
insert into tblBrand (BrandName, CompanyID) values ('simvastatin', 1);
insert into tblBrand (BrandName, CompanyID) values ('ACER SACCHARUM POLLEN', 1);
insert into tblBrand (BrandName, CompanyID) values ('Pain Relief PM', 1);
insert into tblBrand (BrandName, CompanyID) values ('Allopurinol', 1);
insert into tblBrand (BrandName, CompanyID) values ('SEROQUEL', 1);