select * from tblProduct

SELECT * FROM tblProductType 

SELECT * FROM tblBrand

insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Thermazene', 8, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Western Water Hemp', 4, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('health mart adult tussin', 15, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Crest Complete Multi-benefit', 5, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Temazepam', 14, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('LUICHEL SHINY CAKE NO 33', 18, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ondansetron Hydrochloride', 30, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nighttime Sleep Aid', 25, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('ARANESP', 16, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Afeditab', 6, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Hamamelis Virginiana 30c', 14, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Adrenal Support', 15, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ampicillin', 11, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Hydroxyzine Hydrochloride', 19, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('MED NAP CLEANSING', 30, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('smart sense nasal', 4, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Boost Remedy Water', 17, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('SHISEIDO SHEER AND PERFECT FOUNDATION', 4, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('triamcinolone acetonide', 31, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('SENSAI FLUID FINISH LASTING VELVET FV102', 33, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('OXYGEN', 3, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Gabapentin', 20, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('ChapStick Classic Strawberry', 12, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Escitalopram', 3, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Italian Rye Grass', 28, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Gabapentin', 22, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('ERYTHROMYCIN', 31, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Trifluoperazine Hydrochloride', 6, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('HGH PLUS', 28, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nicotine', 22, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nizatidine', 29, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Oxygen', 16, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Naproxen', 4, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Regular Strength Enteric Aspirin', 13, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Palmers Amaranth', 9, 23);

insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Mycobutin', 25, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Potassium Acetate', 8, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('McKesson Unna Boot with Calamine 4', 32, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('GaviLyte - C', 20, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lamb Quarters', 18, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Degree Women', 7, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ibuprofen PM', 5, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Gabapentin', 18, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Morphine Sulfate', 12, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Isosorbide Dinitrate', 3, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Humalog', 18, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pulmozyme', 17, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soothix Psoriasis and Seborrheic Dermatitis Formula', 33, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Granulex', 16, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('flormar Concealer Sunscreen Broad Spectrum SPF 20 LC03 SOFT HONEY', 21, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Head and Shoulders', 29, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Givenchy Fluid Foundation Airy-light Mat Radiance SPF 20 Tint 4', 20, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lamivudine and Zidovudine', 29, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Hydrocortisone', 24, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Oil-Free Acne Wash', 30, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Escitalopram', 25, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('SUPER PLUS PERFECT BB', 25, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Care One Medicated Lip Balm in a Pot', 8, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('FLOVENT', 11, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Arizona Ash', 20, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Benazepril hydrochloride and hydrochlorothiazide', 29, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('amlodipine besylate', 13, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Allermilk', 31, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sting Relief', 17, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Hyoscyamine Sulfate', 32, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('care one anti diarrheal', 32, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Valproic Acid', 2, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Propranolol Hydrochloride', 27, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Doxycycline Hyclate', 32, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Perfect Sleep', 3, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nex Iodio P2', 1, 23);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Foaming Hand Sanitizer', 23, 23);

insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Magnotta - Belpaese', 21, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Crush - Cream Soda', 9, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('The Pop Shoppe - Grape', 25, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Fish - Bones', 28, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Glass - Wine, Plastic, Clear 5 Oz', 17, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Dubouef Macon - Villages', 12, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Tenderloin - Aa', 1, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Kiwi', 29, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tea - Decaf Lipton', 19, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Leeks - Large', 22, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beer - Rickards Red', 21, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Rice Pilaf, Dry,package', 16, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Niagara Peninsula Vqa', 26, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Thyme - Fresh', 9, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tart - Butter Plain Squares', 24, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soup - Campbells, Spinach Crm', 22, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Syrup - Golden, Lyles', 23, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Apple - Custard', 19, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Coffee - Decaffeinato Coffee', 18, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Steamers White', 12, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tuna - Salad Premix', 6, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cheese - Mozzarella, Shredded', 13, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pineapple - Golden', 29, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Phyllo Dough', 20, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Dill Weed - Fresh', 9, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soup - Campbells Asian Noodle', 1, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chicken - Whole', 12, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Mix Pina Colada', 8, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ecolab - Mikroklene 4/4 L', 3, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Plastic Arrow Stir Stick', 27, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Foam Tray S2', 16, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Mushroom Morel Fresh', 8, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Vidal Icewine Magnotta', 18, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Filter - Coffee', 7, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Bones, Cut - Up', 7, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Gherkin', 15, 13);

insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pastry - Mini French Pastries', 4, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beer - Labatt Blue', 16, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Mushroom - Morel Frozen', 16, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bar Energy Chocchip', 25, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Shiraz Wolf Blass Premium', 6, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tomato - Plum With Basil', 14, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread Ww Cluster', 14, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beer - Mcauslan Apricot', 3, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Spice - Pepper Portions', 11, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ice Cream - Fudge Bars', 31, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Water - Green Tea Refresher', 32, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sugar - Crumb', 27, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Salmon - Canned', 2, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Chuck, Boneless', 11, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ham - Virginia', 25, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Red, Colio Cabernet', 14, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Scampi Tail', 30, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Jam - Raspberry,jar', 7, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Couscous', 23, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Pinot Noir Pond Haddock', 20, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread Ww Cluster', 22, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Longos - Chicken Cordon Bleu', 2, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Squash - Pepper', 31, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Syrup - Monin - Blue Curacao', 16, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Pinot Noir Stoneleigh', 24, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cup - 4oz Translucent', 27, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nut - Pumpkin Seeds', 25, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Shrimp - Black Tiger 16/20', 14, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Ej Gallo Sierra Valley', 29, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tomato Puree', 29, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pasta - Penne Primavera, Single', 7, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Gatorade - Fruit Punch', 10, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Assorted Desserts', 2, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Shrimp - 16/20, Iqf, Shell On', 15, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sobe - Tropical Energy', 14, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lamb - Sausage Casings', 24, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Onions - Cooking', 16, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sage - Ground', 15, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soup - Campbells Mushroom', 13, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cheese - St. Andre', 16, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sobe - Cranberry Grapefruit', 6, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Napkin White - Starched', 5, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Maple Syrup', 28, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Garbage Bags - Black', 32, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pork - Sausage Casing', 32, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soda Water - Club Soda, 355 Ml', 9, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Crumbs, Bulk', 14, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Oil - Canola', 11, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chocolate - Milk, Callets', 12, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beer - Creemore', 11, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chilli Paste, Hot Sambal Oelek', 13, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Glass - Wine, Plastic, Clear 5 Oz', 22, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nut - Chestnuts, Whole', 17, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Magnotta - Red, Baco', 9, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Water - Mineral, Carbonated', 8, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bok Choy - Baby', 26, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pasta - Shells, Medium, Dry', 7, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lamb - Ground', 11, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Jolt Cola - Electric Blue', 28, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Truffle Cups - Red', 26, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chocolate - Mi - Amere Semi', 30, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pasta - Detalini, White, Fresh', 20, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Red Pepper Paste', 22, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Crusty Italian Poly', 18, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tia Maria', 9, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Coconut Milk - Unsweetened', 12, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tamarind Paste', 21, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Turkey - Oven Roast Breast', 19, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Capon - Breast, Double, Wing On', 11, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Kippers - Smoked', 13, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Muffin - Mix - Strawberry Rhubarb', 12, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('The Pop Shoppe - Root Beer', 25, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lettuce - Mini Greens, Whole', 14, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Eggplant - Regular', 16, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Liqueur Banana, Ramazzotti', 13, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Foil Wrap', 23, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Jolt Cola', 28, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Radish - Pickled', 7, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Yoplait Drink', 3, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cheese - Gorgonzola', 14, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Onions - Cippolini', 2, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Roasted, Cooked', 2, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Carbonated Water - Strawberry', 29, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Star Fruit', 12, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sprouts Dikon', 15, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Fireball Whisky', 2, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Latex Rubber Gloves Size 9', 18, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Steampan - Lid For Half Size', 27, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Rice - 7 Grain Blend', 7, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Jam - Apricot', 12, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Fireball Whisky', 19, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Veal - Round, Eye Of', 25, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chocolate Bar - Coffee Crisp', 18, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chevril', 14, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chicken - Livers', 15, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cheese - Grana Padano', 19, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Figs', 7, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Sauvignon Blanc Oyster', 26, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sauerkraut', 20, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Icecream - Dstk Strw Chseck', 30, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pork - Kidney', 31, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lid - 0090 Clear', 8, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Appetizer - Cheese Bites', 7, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Pita, Mini', 28, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bagelers', 5, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Island Oasis - Magarita Mix', 13, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beer - Blue', 10, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Table Cloth 62x120 White', 24, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Thyme - Lemon, Fresh', 24, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Glass - Wine, Plastic, Clear 5 Oz', 27, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Garam Masala Powder', 30, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Gin - Gilbeys London, Dry', 27, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Mince Meat - Filling', 6, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Energy Drink Red Bull', 32, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bay Leaf Ground', 24, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Assorted Rolls', 23, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Coffee - French Vanilla Frothy', 28, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Crusty Italian Poly', 26, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pork - Tenderloin, Frozen', 32, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Flour - Bran, Red', 31, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Dried Figs', 9, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lettuce - Iceberg', 19, 15);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ecolab - Mikroklene 4/4 L', 5, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Oregano - Fresh', 17, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sping Loaded Cup Dispenser', 2, 21);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soup - Campbells Beef Strogonoff', 33, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Salt - Table', 11, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Ox Tail, Frozen', 12, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lemonade - Natural, 591 Ml', 18, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Higashimaru Usukuchi Soy', 1, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Onions - Red', 32, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cake - Bande Of Fruit', 4, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Potatoes - Idaho 100 Count', 29, 2);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sauce - Sesame Thai Dressing', 26, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Butcher Twine 4r', 7, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - White, Lindemans Bin 95', 24, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chicken Thigh - Bone Out', 28, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Mushroom - White Button', 3, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Chocolate - Milk', 26, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Juice - Orange 1.89l', 15, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Ketchup - Tomato', 24, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Jameson Irish Whiskey', 10, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Grapes - Green', 27, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Sour Batard', 6, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Schnappes - Peach, Walkers', 19, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Cherries - Fresh', 12, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Trout Rainbow Whole', 31, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Two Oceans Cabernet', 3, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tart - Pecan Butter Squares', 23, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Magnotta - Bel Paese White', 31, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Table Cloth - 53x69 Colour', 22, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tart Shells - Savory, 2', 22, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Squid - Tubes / Tenticles 10/20', 5, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine La Vielle Ferme Cote Du', 1, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread Base - Gold Formel', 17, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wiberg Super Cure', 8, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Curry Powder Madras', 21, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Couscous', 20, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - White, French Cross', 2, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sausage - Blood Pudding', 33, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Milk Powder', 21, 5);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Spinach - Frozen', 16, 10);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Flour - Masa De Harina Mexican', 1, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Salmon - Sockeye Raw', 18, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Syrup - Monin - Blue Curacao', 16, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Salt - Sea', 26, 20);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sauce - Thousand Island', 12, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Alsace Gewurztraminer', 9, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sugar Thermometer', 22, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pork - Butt, Boneless', 13, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Juice - Orange', 3, 13);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Radish - Pickled', 9, 8);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Oil - Margarine', 6, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Juice - Apple, 1.36l', 14, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Shopper Bag - S - 4', 30, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Nantucket - Orange Mango Cktl', 27, 14);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Kindney, Whole', 29, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Fondant - Icing', 14, 1);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Frangelico', 18, 4);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wood Chips - Regular', 28, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Crackers - Graham', 17, 16);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tomatoes - Roma', 19, 18);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pimento - Canned', 23, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Pasta - Lasagne, Fresh', 29, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Leeks - Baby, White', 33, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Island Oasis - Wildberry', 2, 3);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Sun - Dried Tomatoes', 20, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Muffin Batt - Blueberry Passion', 11, 9);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Beef - Flank Steak', 3, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Tamarillo', 11, 22);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Wine - Carmenere Casillero Del', 28, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Icecream - Dstk Strw Chseck', 16, 12);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Bread - Rosemary Focaccia', 6, 19);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Yogurt - Peach, 175 Gr', 14, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Lettuce - Belgian Endive', 3, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Vacuum Bags 12x16', 33, 6);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Juice - Lagoon Mango', 33, 11);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Soup - Campbells Broccoli', 1, 7);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Muffin Carrot - Individual', 2, 17);
insert into tblProduct (ProductName, BrandID, ProductTypeID) values ('Rice - Long Grain', 13, 12);

