-- Populate Product type
BEGIN TRAN populateProductType
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('alcohol', 'this product is a type alcohol')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('tobacco', 'this product is a type tobacco')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('baby', 'this product is a type baby')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('beverages', 'this product is a type beverages')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('bread & bakery', 'this product is a type bread & bakery')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('breakfast & cereal', 'this product is a type breakfast & cereal')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('canned goods & soups', 'this product is a type canned goods & soups')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('condiments/spices & bake', 'this product is a type condiments/spices & bake')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('cookies, snacks & candy', 'this product is a type cookies, snacks & candy')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('dairy, eggs & cheese', 'this product is a type dairy, eggs & cheese')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('deli & signature cafe', 'this product is a type deli & signature cafe')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('flowers', 'this product is a type flowers')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('frozen foods', 'this product is a type frozen foods')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('produce', 'this product is a type produce')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('grains, pasta & sides', 'this product is a type grains, pasta & sides')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('international cuisine', 'this product is a type international cuisine')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('meat & seafood', 'this product is a type meat & seafood')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('miscellaneous', 'this product is a type miscellaneous')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('paper products', 'this product is a type paper products')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('cleaning supplies', 'this product is a type cleaning supplies')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('health & beauty, personal care & pharmacy', 'this product is a type health & beauty, personal care & pharmacy')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('pet care', 'this product is a type pet care')
    INSERT INTO tblProductType(ProductTypeName, ProductTypeDescription)
    VALUES ('pharmacy', 'this product is a type pharmacy')
COMMIT TRAN populateProductType