USE INFO330_PROJ_A13
BEGIN TRAN populatetblCompany
insert into tblCompany (CompanyName) values ('Sporer Group');
insert into tblCompany (CompanyName) values ('Franecki, Lynch and Kerluke');
insert into tblCompany (CompanyName) values ('Halvorson-Beahan');
insert into tblCompany (CompanyName) values ('Bergstrom, King and Bechtelar');
insert into tblCompany (CompanyName) values ('Schuppe, Fadel and Nienow');
insert into tblCompany (CompanyName) values ('Gutmann Group');
insert into tblCompany (CompanyName) values ('Shields Inc');
insert into tblCompany (CompanyName) values ('Runolfsson-Olson');
insert into tblCompany (CompanyName) values ('Leuschke-Lebsack');
insert into tblCompany (CompanyName) values ('Little, Barton and Hoppe');
insert into tblCompany (CompanyName) values ('Feeney-Jast');
insert into tblCompany (CompanyName) values ('Harvey and Sons');
insert into tblCompany (CompanyName) values ('Witting, Kessler and Keeling');
insert into tblCompany (CompanyName) values ('Legros Group');
insert into tblCompany (CompanyName) values ('Marquardt-Hilll');
insert into tblCompany (CompanyName) values ('Tillman, Mohr and Mueller');
insert into tblCompany (CompanyName) values ('Yost Inc');
insert into tblCompany (CompanyName) values ('Kohler Inc');
insert into tblCompany (CompanyName) values ('Roob LLC');
insert into tblCompany (CompanyName) values ('Johns, Medhurst and Orn');
insert into tblCompany (CompanyName) values ('Connelly-Baumbach');
insert into tblCompany (CompanyName) values ('Hamill-Huels');
insert into tblCompany (CompanyName) values ('Cassin, Gerhold and Pfannerstill');
insert into tblCompany (CompanyName) values ('Mante and Sons');
insert into tblCompany (CompanyName) values ('Morissette Inc');
insert into tblCompany (CompanyName) values ('Steuber Group');
insert into tblCompany (CompanyName) values ('Kshlerin-Upton');
insert into tblCompany (CompanyName) values ('Jast and Sons');
insert into tblCompany (CompanyName) values ('Little, Gutmann and Bogan');
insert into tblCompany (CompanyName) values ('Konopelski-Balistreri');
insert into tblCompany (CompanyName) values ('Anderson-Reynolds');
insert into tblCompany (CompanyName) values ('Schinner-VonRueden');
insert into tblCompany (CompanyName) values ('Windler, MacGyver and Goyette');
insert into tblCompany (CompanyName) values ('Raynor, Dibbert and Fay');
insert into tblCompany (CompanyName) values ('Nader-Shields');
insert into tblCompany (CompanyName) values ('Tillman Group');
insert into tblCompany (CompanyName) values ('Zboncak Group');
insert into tblCompany (CompanyName) values ('Funk and Sons');
insert into tblCompany (CompanyName) values ('Fritsch, Ziemann and Rodriguez');
insert into tblCompany (CompanyName) values ('Wolf-Bednar');
insert into tblCompany (CompanyName) values ('Jacobi, Zboncak and Grimes');
insert into tblCompany (CompanyName) values ('Dickinson and Sons');
insert into tblCompany (CompanyName) values ('Grimes and Sons');
insert into tblCompany (CompanyName) values ('Romaguera-Feest');
insert into tblCompany (CompanyName) values ('Leuschke, Waters and Lowe');
insert into tblCompany (CompanyName) values ('Conroy LLC');
insert into tblCompany (CompanyName) values ('Rosenbaum-Braun');
insert into tblCompany (CompanyName) values ('Denesik Inc');
insert into tblCompany (CompanyName) values ('Greenholt Inc');
insert into tblCompany (CompanyName) values ('Grimes, Zieme and Raynor');
insert into tblCompany (CompanyName) values ('Marquardt-Grady');
insert into tblCompany (CompanyName) values ('Parisian, Wisozk and Connelly');
insert into tblCompany (CompanyName) values ('Stroman-Torp');
insert into tblCompany (CompanyName) values ('MacGyver-Towne');
insert into tblCompany (CompanyName) values ('Ruecker-Berge');
insert into tblCompany (CompanyName) values ('Ledner, Hartmann and Bartell');
insert into tblCompany (CompanyName) values ('Graham LLC');
insert into tblCompany (CompanyName) values ('Schultz and Sons');
insert into tblCompany (CompanyName) values ('Lindgren-Sanford');
insert into tblCompany (CompanyName) values ('Kovacek, Weber and Johns');
insert into tblCompany (CompanyName) values ('Weissnat-Adams');
insert into tblCompany (CompanyName) values ('Schumm-Kessler');
insert into tblCompany (CompanyName) values ('Cole-Ruecker');
insert into tblCompany (CompanyName) values ('Marks Inc');
insert into tblCompany (CompanyName) values ('Terry, Lang and Mitchell');
insert into tblCompany (CompanyName) values ('Kozey LLC');
insert into tblCompany (CompanyName) values ('Douglas-Kihn');
insert into tblCompany (CompanyName) values ('Dare Group');
insert into tblCompany (CompanyName) values ('Witting, Parisian and Crona');
insert into tblCompany (CompanyName) values ('Barton-Bergstrom');
insert into tblCompany (CompanyName) values ('Stark Inc');
insert into tblCompany (CompanyName) values ('Kessler, Aufderhar and Cormier');
insert into tblCompany (CompanyName) values ('Erdman-Bashirian');
insert into tblCompany (CompanyName) values ('Jast Inc');
insert into tblCompany (CompanyName) values ('Gerhold-Klocko');
insert into tblCompany (CompanyName) values ('Dicki-Kihn');
insert into tblCompany (CompanyName) values ('Barton LLC');
insert into tblCompany (CompanyName) values ('Lesch, Reinger and Hickle');
insert into tblCompany (CompanyName) values ('Strosin Inc');
insert into tblCompany (CompanyName) values ('Keebler-Hammes');
insert into tblCompany (CompanyName) values ('Bashirian and Sons');
insert into tblCompany (CompanyName) values ('Price-Romaguera');
insert into tblCompany (CompanyName) values ('Muller, Hirthe and Hegmann');
insert into tblCompany (CompanyName) values ('Hickle LLC');
insert into tblCompany (CompanyName) values ('Lubowitz Inc');
insert into tblCompany (CompanyName) values ('Cormier, Gusikowski and Bartell');
insert into tblCompany (CompanyName) values ('Prosacco, Hessel and Stark');
insert into tblCompany (CompanyName) values ('McClure, Lueilwitz and Gutmann');
insert into tblCompany (CompanyName) values ('Armstrong, Mraz and Langosh');
insert into tblCompany (CompanyName) values ('Morissette, Grady and Watsica');
insert into tblCompany (CompanyName) values ('Miller-Dooley');
insert into tblCompany (CompanyName) values ('Nikolaus-Rutherford');
insert into tblCompany (CompanyName) values ('Ward LLC');
insert into tblCompany (CompanyName) values ('Kunze Inc');
insert into tblCompany (CompanyName) values ('Funk, Hansen and Steuber');
insert into tblCompany (CompanyName) values ('Schneider Group');
insert into tblCompany (CompanyName) values ('Bosco and Sons');
insert into tblCompany (CompanyName) values ('Haley-Pouros');
insert into tblCompany (CompanyName) values ('Nolan-Abernathy');
insert into tblCompany (CompanyName) values ('Hills-Bradtke');
Commit populatetblCompany