
USE INFO330_PROJ_A13
BEGIN TRAN populateBrand
insert into tblBrand (BrandName, CompanyID) values ('Raisin - Golden', 28);
insert into tblBrand (BrandName, CompanyID) values ('Pastry - Lemon Danish - Mini', 65);
insert into tblBrand (BrandName, CompanyID) values ('Nantucket - Orange Mango Cktl', 73);
insert into tblBrand (BrandName, CompanyID) values ('Fennel - Seeds', 2);
insert into tblBrand (BrandName, CompanyID) values ('Flour - So Mix Cake White', 92);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Chateau Aqueria Tavel', 95);
insert into tblBrand (BrandName, CompanyID) values ('Cocoa Butter', 4);
insert into tblBrand (BrandName, CompanyID) values ('Catfish - Fillets', 21);
insert into tblBrand (BrandName, CompanyID) values ('Bay Leaf Fresh', 97);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Clamato, 341 Ml', 56);
insert into tblBrand (BrandName, CompanyID) values ('Brandy Apricot', 74);
insert into tblBrand (BrandName, CompanyID) values ('Carrots - Mini Red Organic', 81);
insert into tblBrand (BrandName, CompanyID) values ('Pate - Liver', 16);
insert into tblBrand (BrandName, CompanyID) values ('Steampan - Half Size Shallow', 33);
insert into tblBrand (BrandName, CompanyID) values ('Pastry - Baked Scones - Mini', 93);
insert into tblBrand (BrandName, CompanyID) values ('Cotton Wet Mop 16 Oz', 65);
insert into tblBrand (BrandName, CompanyID) values ('Energy Drink', 54);
insert into tblBrand (BrandName, CompanyID) values ('Plums - Red', 37);
insert into tblBrand (BrandName, CompanyID) values ('Onions - Red Pearl', 73);
insert into tblBrand (BrandName, CompanyID) values ('Radish', 96);
insert into tblBrand (BrandName, CompanyID) values ('Vinegar - Balsamic, White', 85);
insert into tblBrand (BrandName, CompanyID) values ('Grand Marnier', 10);
insert into tblBrand (BrandName, CompanyID) values ('Miso - Soy Bean Paste', 19);
insert into tblBrand (BrandName, CompanyID) values ('Lighter - Bbq', 55);
insert into tblBrand (BrandName, CompanyID) values ('Vaccum Bag 10x13', 97);
insert into tblBrand (BrandName, CompanyID) values ('Tomatoes - Heirloom', 22);
insert into tblBrand (BrandName, CompanyID) values ('Cornish Hen', 43);
insert into tblBrand (BrandName, CompanyID) values ('Potatoes - Pei 10 Oz', 78);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Chablis J Moreau Et Fils', 21);
insert into tblBrand (BrandName, CompanyID) values ('Bread Base - Goodhearth', 11);
insert into tblBrand (BrandName, CompanyID) values ('Asparagus - Green, Fresh', 2);
insert into tblBrand (BrandName, CompanyID) values ('Chilli Paste, Sambal Oelek', 64);
insert into tblBrand (BrandName, CompanyID) values ('Milk - Buttermilk', 40);
insert into tblBrand (BrandName, CompanyID) values ('Sausage - Blood Pudding', 58);
insert into tblBrand (BrandName, CompanyID) values ('Snapple - Mango Maddness', 90);
insert into tblBrand (BrandName, CompanyID) values ('Brownies - Two Bite, Chocolate', 94);
insert into tblBrand (BrandName, CompanyID) values ('Herb Du Provence - Primerba', 83);
insert into tblBrand (BrandName, CompanyID) values ('Carbonated Water - Peach', 4);
insert into tblBrand (BrandName, CompanyID) values ('Split Peas - Green, Dry', 28);
insert into tblBrand (BrandName, CompanyID) values ('Sparkling Wine - Rose, Freixenet', 62);
insert into tblBrand (BrandName, CompanyID) values ('Sproutsmustard Cress', 53);
insert into tblBrand (BrandName, CompanyID) values ('Papayas', 40);
insert into tblBrand (BrandName, CompanyID) values ('Cloves - Whole', 39);
insert into tblBrand (BrandName, CompanyID) values ('Smoked Paprika', 68);
insert into tblBrand (BrandName, CompanyID) values ('Bread Fig And Almond', 2);
insert into tblBrand (BrandName, CompanyID) values ('Flour - Rye', 88);
insert into tblBrand (BrandName, CompanyID) values ('Chicken - Bones', 58);
insert into tblBrand (BrandName, CompanyID) values ('Cheese - Mozzarella', 48);
insert into tblBrand (BrandName, CompanyID) values ('Grapes - Black', 36);
insert into tblBrand (BrandName, CompanyID) values ('Tomatoes - Heirloom', 19);
insert into tblBrand (BrandName, CompanyID) values ('Lamb - Leg, Bone In', 78);
insert into tblBrand (BrandName, CompanyID) values ('Oil - Truffle, White', 99);
insert into tblBrand (BrandName, CompanyID) values ('Sour Cream', 3);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Savigny - Les - Beaune', 25);
insert into tblBrand (BrandName, CompanyID) values ('Sansho Powder', 84);
insert into tblBrand (BrandName, CompanyID) values ('Rosemary - Primerba, Paste', 47);
insert into tblBrand (BrandName, CompanyID) values ('Toamtoes 6x7 Select', 18);
insert into tblBrand (BrandName, CompanyID) values ('Broom - Corn', 83);
insert into tblBrand (BrandName, CompanyID) values ('Ice Cream Bar - Oreo Cone', 81);
insert into tblBrand (BrandName, CompanyID) values ('Oil - Food, Lacquer Spray', 51);
insert into tblBrand (BrandName, CompanyID) values ('Potatoes - Mini Red', 77);
insert into tblBrand (BrandName, CompanyID) values ('Pesto - Primerba, Paste', 85);
insert into tblBrand (BrandName, CompanyID) values ('Corn - Mini', 52);
insert into tblBrand (BrandName, CompanyID) values ('Pasta - Elbows, Macaroni, Dry', 12);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Chateau Aqueria Tavel', 95);
insert into tblBrand (BrandName, CompanyID) values ('Bread - Multigrain Oval', 79);
insert into tblBrand (BrandName, CompanyID) values ('Syrup - Monin - Passion Fruit', 70);
insert into tblBrand (BrandName, CompanyID) values ('Vodka - Moskovskaya', 37);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Niagara Peninsula Vqa', 34);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - Baby, Warm Water', 89);
insert into tblBrand (BrandName, CompanyID) values ('Doilies - 8, Paper', 39);
insert into tblBrand (BrandName, CompanyID) values ('Buttons', 5);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Prosecco Valdobienne', 6);
insert into tblBrand (BrandName, CompanyID) values ('Canadian Emmenthal', 65);
insert into tblBrand (BrandName, CompanyID) values ('Cookie Dough - Chunky', 2);
insert into tblBrand (BrandName, CompanyID) values ('Nut - Pine Nuts, Whole', 96);
insert into tblBrand (BrandName, CompanyID) values ('Soup - Campbells, Beef Barley', 54);
insert into tblBrand (BrandName, CompanyID) values ('Butter - Salted, Micro', 64);
insert into tblBrand (BrandName, CompanyID) values ('Butter Ripple - Phillips', 11);
insert into tblBrand (BrandName, CompanyID) values ('Shrimp - 16/20, Peeled Deviened', 38);
insert into tblBrand (BrandName, CompanyID) values ('Brownies - Two Bite, Chocolate', 40);
insert into tblBrand (BrandName, CompanyID) values ('Juice - Orange, 341 Ml', 57);
insert into tblBrand (BrandName, CompanyID) values ('Ham - Virginia', 19);
insert into tblBrand (BrandName, CompanyID) values ('Monkfish - Fresh', 88);
insert into tblBrand (BrandName, CompanyID) values ('Flour Pastry Super Fine', 15);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Hardys Bankside Shiraz', 69);
insert into tblBrand (BrandName, CompanyID) values ('Veal - Shank, Pieces', 21);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Magnotta - Bel Paese White', 23);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Red, Cabernet Sauvignon', 84);
insert into tblBrand (BrandName, CompanyID) values ('Longos - Greek Salad', 15);
insert into tblBrand (BrandName, CompanyID) values ('Jolt Cola', 70);
insert into tblBrand (BrandName, CompanyID) values ('Beans - Long, Chinese', 63);
insert into tblBrand (BrandName, CompanyID) values ('Apron', 3);
insert into tblBrand (BrandName, CompanyID) values ('Asparagus - Frozen', 89);
insert into tblBrand (BrandName, CompanyID) values ('Wine - Dubouef Macon - Villages', 50);
insert into tblBrand (BrandName, CompanyID) values ('Flavouring - Raspberry', 31);
insert into tblBrand (BrandName, CompanyID) values ('Longos - Assorted Sandwich', 67);
insert into tblBrand (BrandName, CompanyID) values ('Praline Paste', 36);
insert into tblBrand (BrandName, CompanyID) values ('Tart Shells - Savory, 4', 56);
insert into tblBrand (BrandName, CompanyID) values ('Muffin Puck Ww Carrot', 80);
COMMIT TRAN populateBrand